### ISSUE TITLE
Question about flipping iRules.

### ISSUE THREAD

**Issue by Nino55N** [swalberg/f5-icontrol#6]
Is there a way to use this gem to apply a new list of rules to a virtual server?

**Comment by Nino55N** [comment]
And if not is there a way to make a generic api call using this gem? I was unable to find one

**Comment by swalberg** [comment]
For sure. Have a look at https://devcentral.f5.com/wiki/iControl.LocalLB__VirtualServer__add_rule.ashx for the SOAP interface to add a rule.

The sample code at the bottom of the article has some stuff that might help. Just remember it's using a slightly different convention than this gem, so you'll want to translate. e.g. `bigip["LocalLB.VirtualServer"].get_list` would be `bigip.LocalLB.VirtualServer.get_list`, and when passing values you need to add `item:` kind of like [this](https://github.com/swalberg/chef-f5/blob/master/libraries/chef_f5.rb#L87-L90)

**Comment by swalberg** [comment]
Generic API calls - see https://github.com/swalberg/f5-icontrol#usage

Also note that the released branch uses the SOAP interface. I'm in the process of adding support for the REST interface in the [REST branch](https://github.com/swalberg/f5-icontrol/tree/REST)

**Comment by Nino55N** [comment]
Awesome! Currently our F5 API is soap unfortunately :( but I do appreciate the help. I will comment back here if I have any more questions but I am going to go ahead and close this.

**Comment by Nino55N** [comment]
@swalberg Is there anything I have to do to require this in my ruby modules? I have tried require 'f5/icontrol' and 'f5-icontrol' but am coming up short.

**Comment by Nino55N** [comment]
@swalberg I think in order to add new rules you have to create a VirtualServerRule object like so
```
iRule = api.LocalLB.VirtualServer.VirtualServerRule.new
``` 
however it looks like the VirtualServer class does not support this. Is there another way to create this object?

**Comment by swalberg** [comment]
Hi, despite the capitalization, these aren't classes. This gem is just a thin wrapper around the SOAP API method calls. I didn't see that there were any objects I could use.

To add a rule to a VIP, you'd want something like:
```Ruby
api.LocalLB.VirtualServer.add_rule (
 virtual_servers: { item: [ '/Common/myvip'] },
 rules: {  
   item: [
     item: {
        rule_name: 'myrule',
        priority: 42
     }
   ]
 }
)```

(haven't tried it, just going on the docs)

**Comment by Nino55N** [comment]
I think I am very close and that is what I am looking for. However I am getting a strange error when trying to execute some code:
```
api.LocalLB.VirtualServer.add_rule('asdf','asdf')
```

Now I know that it should error out because these aren't virtual servers but instead it gives me this error:
```
ArgumentError: wrong number of arguments (3 for 1..2)
from ...gems/ruby-2.2.3/gems/f5-icontrol-0.1.6/lib/f5/icontrol/api.rb:15:in `method_missing'
```
From what investigation I have done so far if I only pass one argument in the add_rule method to get past this error. However, I believe I need to pass two according to the docs.

**Comment by swalberg** [comment]
The [API docs](https://devcentral.f5.com/wiki/iControl.LocalLB__VirtualServer__add_rule.ashx) for that call say it gets passed two elements... `virtual_servers` and `rules`. It's not very intuitive, possibly because I'm not using the intermediate SOAP objects and just sending data structures.

Savon does some magic in the middle which is why I'm guessing you're getting an error for 3 args when you clearly passed 2. But it's expecting a hash, not two strings.

**Comment by Nino55N** [comment]
Ah I think I figured it out, it actually takes one parameter but the hash that it takes just has two key value pairs. One being the virtual servers and one being the rules. Which I now realize was part of the example you put up above :/ Sorry about that. Thanks again for the help.
