### ISSUE TITLE
LocalLB.Pool get_member_v1 doesn't seem to work properly

### ISSUE THREAD

**Issue by ssherman** [swalberg/f5-icontrol#9]
`pool_api.api.get_member_v2(pool_names: {item: ["bkbvdstest1wss"]})`

returns:

`{:item=>{:"@a:array_type"=>"iControl:Common.AddressPort[0]"}, :"@s:type"=>"A:Array", :"@a:array_type"=>"iControl:Common.AddressPort[][1]"}`

**Comment by ssherman** [comment]
aaah actually. it looks like that pool doesn't have any members!

**Comment by swalberg** [comment]
That'll do it!
